name: Generate snake animation

on:
  schedule:
    - cron: "* */12 * * *"  # Runs every 12 hours

  workflow_dispatch:  # Allows manual triggering

  push:
    branches:
      - master  # Runs when changes are pushed to the master branch

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ skavi7904 }}  # Uses the repository owner's username
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Pushes to the output branch
          build_dir: dist  # Directory where the SVG is stored
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authentication token
